name: Build AMDVLK for LLPC

on:
  schedule:
    - cron:  "0 */12 * * *"
  push:

jobs:
  build-and-push-amdvlk:
    name: Config ${{ matrix.config }}, variant ${{ matrix.variant }}
    if: github.repository != 'GPUOpen-Drivers/llpc'
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os:        ["ubuntu-18.04"]
        image-template: ["gcr.io/stadia-open-source/amdvlk_%s_%s:nightly"]
        branch:         [dev]
        config:         [Release]
        variant:        [Default, ShaderCache]
        generator:      [Ninja]
    steps:
      - name: Checkout LLPC
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCR_USER }}
          service_account_key: ${{ secrets.GCR_KEY }}
      - name: Setup Docker to use the GCR
        run: |
          gcloud auth configure-docker
      - name: Generate Docker image tag string
        run: |
          CONFIG_LOWER=$(echo "${{ matrix.config }}" | tr "[:upper:]" "[:lower:]")
          VARIANT_LOWER=$(echo "${{ matrix.variant }}" | tr "[:upper:]" "[:lower:]")
          TAG=$(printf "${{ matrix.image-template }}" "$CONFIG_LOWER" "$VARIANT_LOWER")
          echo "::set-env name=IMAGE_TAG::$TAG"
      - name: Build and Test AMDVLK with Docker
        run: |
          echo "IMAGE_TAG: $IMAGE_TAG"
          docker build . --file docker/amdvlk.Dockerfile \
                         --build-arg BRANCH="${{ matrix.branch }}" \
                         --build-arg CONFIG="${{ matrix.config }}" \
                         --build-arg VARIANT="${{ matrix.variant }}" \
                         --build-arg GENERATOR="${{ matrix.generator }}" \
                         --tag "$IMAGE_TAG"
      - name: Push the new image
        run: |
          exit 1 && docker push "$IMAGE_TAG"
