name: LLPC Docker CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:

jobs:
  build-and-test:
    name: Variant ${{ matrix.base-image-variant }}
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os:             ["ubuntu-18.04"]
        base-image-template: ["gcr.io/stadia-open-source/amdvlk_%s:nightly"]
        base-image-variant:  ["release_default", "release_shadercache"]
    steps:
      - name: Checkout LLPC
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git fetch origin +${GITHUB_SHA}:${GITHUB_REF} --update-head-ok
          git checkout ${GITHUB_SHA}
      - name: Generate Docker base image tag string
        run: |
          TAG=$(printf "${{ matrix.base-image-template }}" "${{ matrix.base-image-variant }}")
          echo "IMAGE_TAG: $TAG"
          echo "::set-env name=IMAGE_TAG::$TAG"
      - name: Fetch the latest prebuilt AMDVLK
        run: docker pull "$IMAGE_TAG"
      - name: Build and Test with Docker
        run: docker build . --file docker/llpc.Dockerfile
                            --build-arg AMDVLK_IMAGE="$IMAGE_TAG"
                            --build-arg LLPC_REPO_NAME="${GITHUB_REPOSITORY}"
                            --build-arg LLPC_REPO_REF="${GITHUB_REF}"
                            --build-arg LLPC_REPO_SHA="${GITHUB_SHA}"
                            --tag llpc/ci-shaderdb
